<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Abhay-Gope" failures="1" tests="4" name="com.admin.AddEmployee_TC_01_test" time="20.744" errors="0" timestamp="2023-11-27T12:18:57 IST" skipped="3">
  <testcase classname="com.admin.AddEmployee_TC_01_test" name="tc_01_test" time="7.152">
    <skipped/>
  </testcase> <!-- tc_01_test -->
  <system-out>
[ Test script execution starts from here. ] tc_01_test [ Test script execution got skipped. ]  </system-out>
  <testcase classname="com.admin.AddEmployee_TC_01_test" name="tc_01_test" time="4.343">
    <skipped/>
  </testcase> <!-- tc_01_test -->
  <system-out>
[ Test script execution starts from here. ] tc_01_test [ Test script execution got skipped. ]  </system-out>
  <testcase classname="com.admin.AddEmployee_TC_01_test" name="tc_01_test" time="3.966">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at com.admin.AddEmployee_TC_01_test.tc_01_test(AddEmployee_TC_01_test.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc_01_test -->
  <system-out>
[ Test script execution starts from here. ] tc_01_test [ Test script execution got failed. ]  </system-out>
  <testcase classname="com.admin.AddEmployee_TC_01_test" name="tc_01_test" time="5.283">
    <skipped/>
  </testcase> <!-- tc_01_test -->
  <system-out>
[ Test script execution starts from here. ] tc_01_test [ Test script execution got skipped. ]  </system-out>
</testsuite> <!-- com.admin.AddEmployee_TC_01_test -->
